name: deploy-to-pages
run-name: ${{ github.actor }} has deployed a new version of Ai web-app

on:
 pull_request:
    branches: 
      - main
    types: [closed]

permissions:
  contents: write
  
jobs:
  build-and-deploy:
    if: ${{ github.event.pull_request.merged }} # only run the workflow if the PR is merged into main branch
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Setup node'
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install and Build 🔧
        run: |
          npm ci
          npm run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # The folder the action should deploy.